'(zzz-to-char (:fetcher "github" :repo "mrkkrp/zzz-to-char" :files nil)
  zygospore (:fetcher "github" :repo "LouisKottmann/zygospore.el" :files nil)
  zweilight-theme (:fetcher "github" :repo "philiparvidsson/Zweilight-Theme-for-Emacs" :files nil)
  ztree (:fetcher "github" :repo "fourier/ztree" :files nil)
  zprint-mode (:fetcher "github" :repo "pesterhazy/zprint-mode.el" :files nil)
 )
