'(zzz-to-char (:fetcher "github" :repo nil :files nil)
  zygospore (:fetcher "github" :repo nil :files nil)
  zweilight-theme (:fetcher "github" :repo nil :files nil)
  ztree (:fetcher "github" :repo nil :files nil)
  zprint-mode (:fetcher "github" :repo nil :files nil)
 )
