#+title: feather-recipes.el
#+author: Naoya Yamashita
#+date: <2018-10-25 Thu>

[[https://github.com/conao3/feather-recipes.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/feather-recipes.el.png]]
[[https://github.com/conao3/feather-recipes.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/feather-recipes.el.svg?style=flat-square]]
[[https://github.com/conao3/feather-recipes.el/releases][https://img.shields.io/github/tag/conao3/feather-recipes.el.svg?style=flat-square]]

* Overview

feather-recipes.el provides the package recipe repository for [[https://github.com/conao3/feather.el][feather.el]], a lightweight Emacs package manager.

This repository contains recipe definitions that specify how to fetch and build packages from various sources, enabling feather.el to manage package installations efficiently.

* Table of Contents

- [[#overview][Overview]]
- [[#installation][Installation]]
- [[#usage][Usage]]
- [[#recipe-format][Recipe Format]]
- [[#contributing][Contributing]]
- [[#license][License]]

* Installation

feather-recipes.el is automatically fetched by feather.el when needed. No manual installation is required for typical usage.

If you want to use a local copy or contribute to the recipes:

#+begin_src shell
git clone https://github.com/conao3/feather-recipes.el.git
#+end_src

* Usage

The recipes in this repository are consumed by feather.el. Once feather.el is installed and configured, it will automatically access these recipes to resolve package dependencies and fetch sources.

For details on using feather.el itself, see the [[https://github.com/conao3/feather.el][feather.el documentation]].

* Recipe Format

Each recipe specifies the source location and build instructions for an Emacs package. The recipe format follows conventions similar to other Emacs package recipe systems.

* Contributing

Contributions are welcome. To add or update a recipe:

1. Fork this repository
2. Add or modify the recipe file
3. Test the recipe with feather.el
4. Submit a pull request

Please ensure your recipes follow the existing conventions in this repository.

* License

#+begin_example
Affero General Public License Version 3 (AGPLv3)
Copyright (c) Naoya Yamashita - https://conao3.com
https://github.com/conao3/feather-recipes.el/blob/master/LICENSE
#+end_example

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
